enabled: true
replicaCount: 1
image:
  repository: thsjowi/otp
  tag: "latest"
  pullPolicy: Always
containerPort: 8085
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
