enabled: true
replicaCount: 1
image:
  repository: thsjowi/config
  tag: "1.0.0"
  pullPolicy: Always
containerPort: 8888
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
