# helm/my-app/Chart.yaml
apiVersion: v2
name: THISJOWI-HELM-CHART
description: Umbrella chart - Password Manager, OTP, Notes, Messages
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  # Tus microservicios (locales)
  - name: config-server
    version: "0.1.0"
    repository: "file://charts/config-server"
    condition: config-server.enabled

  - name: password-manager
    version: "0.1.0"
    repository: "file://charts/password-manager"
    condition: password-manager.enabled

  - name: otp-service
    version: "0.1.0"
    repository: "file://charts/otp-service"
    condition: otp-service.enabled

  - name: notes-service
    version: "0.1.0"
    repository: "file://charts/notes-service"
    condition: notes-service.enabled

  - name: messages-service
    version: "0.1.0"
    repository: "file://charts/messages-service"
    condition: messages-service.enabled

  - name: auth-service
    version: "0.1.0"
    repository: "file://charts/auth-service"
    condition: auth-service.enabled

  # Infraestructura (charts externos)
  - name: cockroachdb
    version: "19.0.6"
    repository: "https://charts.cockroachdb.com"
    condition: cockroachdb.enabled

  - name: kafka
    version: "26.8.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled

  - name: cassandra
    version: "10.5.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: cassandra.enabled

  - name: redis # KeyDB es compatible con el chart de Redis
    version: "18.19.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
