enabled: true
replicaCount: 1
image:
  repository: thsjowi/password
  tag: "latest"
  pullPolicy: Always
containerPort: 8084
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
