apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db-port: {{ .Values.secrets.dbPort | quote }}
  db-username: {{ .Values.secrets.dbUsername | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  redis-port: {{ .Values.secrets.redisPort | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  kafka-host: {{ .Values.secrets.kafkaHost | quote }}
  kafka-port: {{ .Values.secrets.kafkaPort | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  mail-username: {{ .Values.secrets.mailUsername | quote }}
  mail-password: {{ .Values.secrets.mailPassword | quote }}
  mail-sender-email: {{ .Values.secrets.mailSenderEmail | quote }}
  mail-sender-name: {{ .Values.secrets.mailSenderName | quote }}
  google-client-id: {{ .Values.secrets.googleClientId | quote }}
  google-client-secret: {{ .Values.secrets.googleClientSecret | quote }}
  github-client-id: {{ .Values.secrets.githubClientId | quote }}
  github-client-secret: {{ .Values.secrets.githubClientSecret | quote }}
  cassandra-username: {{ .Values.secrets.cassandraUsername | quote }}
  cassandra-password: {{ .Values.secrets.cassandraPassword | quote }}

  auth: {{ .Values.secrets.auth | quote }}